services:
    gaia_db:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: gaia_db
        healthcheck:
            test: pg_isready -U postgres -h localhost
            interval: 5s
            timeout: 5s
            retries: 10
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
            PGDATA: /var/lib/postgresql/data
        ports:
            - "5432:5432"
        volumes:
            - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
            - ./dbdata:/var/lib/postgresql/data
        command:
            [
                "postgres",
                "-c",
                "shared_preload_libraries=pg_cron",
                "-c",
                "cron.database_name=${DB_DATABASE}",
                "-c",
                "default_text_search_config='pg_catalog.portuguese'",
            ]
        deploy:
            resources:
                limits:
                    cpus: "0.45"
                    memory: "250MB"
