version: "3"
services:
    evolution-api:
        container_name: evolution_api
        image: atendai/evolution-api:v2.1.1
        restart: always
        ports:
            - "8081:8081"
        env_file:
            - .env
        volumes:
            - evolution_instances:/evolution/instances

volumes:
    evolution_instances:
