linters:
    presets:
        - bugs
        - performance
        - style
        - format
        - import
        - complexity
    disable:
        - depguard
        - wsl
        - forcetypeassert
        - errcheck

linters-settings:
    tagliatelle:
        case:
            rules:
                json: snake

    varnamelen:
        max-distance: 6
        min-name-length: 2
        ignore-names:
            - id
            - err

    ireturn:
        allow:
            - anon
            - error
            - empty
            - stdlib
            - (Response)$
